# Generated by Django 5.0.3 on 2024-04-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
