# Generated by Django 5.0.3 on 2024-04-25 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_subsciption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsciption',
            new_name='Subscriber',
        ),
    ]
