# Generated by Django 5.0.3 on 2024-06-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name_en_us',
            field=models.CharField(max_length=68, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='article',
            name='name_ru',
            field=models.CharField(max_length=68, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_en_us',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
