# Generated by Django 5.0.3 on 2024-06-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_article_name_en_us_article_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=68, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name_en_us',
            field=models.CharField(max_length=68, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name_ru',
            field=models.CharField(max_length=68, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_en_us',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
