# Generated by Django 5.0.3 on 2024-06-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_article_category_en_article_category_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category_en',
            new_name='category_en_us',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name_en',
            new_name='name_en_us',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_en',
            new_name='text_en_us',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='name_en_us',
        ),
    ]
